spring:
  datasource:
    data: classpath:schema.sql
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    livereload:
      enabled: true
logging:
  level:
    org.hibernate.type: trace